# SPDX-FileCopyrightText: 2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1
SPDX-PackageName = "homebrew-tap"

[[annotations]]
  path = "**"
  precedence = "aggregate"
  SPDX-FileCopyrightText = "2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>"
  SPDX-License-Identifier = "GPL-3.0-or-later"
