# This file was generated by GoReleaser. DO NOT EDIT.
cask "tubenoisseur" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "802dd6bb6caa5e45db16027f595ef5ca49672f757628deb52c7b3a5995401ed9"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "502876a4046726ed052305e22b9cd33807d5e7f941e77f7ae16526d6d6a0cee6"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "63db077e3bade4d48d067785dcd21e4be2017a3535942c28124a657c932f708e"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3de683118dbc7317635012354352981dd71965c1d7c228472508b4a5e4348704"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Linux_arm64.tar.gz"
    end
  end

  name "tubenoisseur"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tubenoisseur"
  bash_completion "completions/bash"
  fish_completion "completions/fish"
  zsh_completion "completions/zsh"

  # No zap stanza required

end
