# This file was generated by GoReleaser. DO NOT EDIT.
cask "tubenoisseur" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "3b105375f1f41e40452275e959b686f539705ab66f2b58843e26d49c90c8ea99"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "238912ba2bfd01f9f99e98206b5c893cc375033d8f89bbf64acc43eda1f233de"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "143b8bab103cba6db49d6bc078cb9a9762bc23ff37cb76a7e14458a4ace8b26c"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "40bfa7240b52031c188565e36a48963aba517f09148ad0d5b1bf6d3096eb1a17"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Linux_arm64.tar.gz"
    end
  end

  name "tubenoisseur"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tubenoisseur"
  bash_completion "completions/bash"
  fish_completion "completions/fish"
  zsh_completion "completions/zsh"

  # No zap stanza required

end
