# This file was generated by GoReleaser. DO NOT EDIT.
cask "tubenoisseur" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "8c502b65e1e66c20e3a6aa0ce5d718ac96076d4ca5f7af9b87eb8aeb0cd86df4"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f5c758e3c3f3df42beba51d3dfcaa0604b96e60b294140b0a215a938cd101b39"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bfad25c57bfdd149441bdeb9b47a4331f95ed67e2398b4756ca165e8d042f2cb"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7ed85975eebc55a1099f322d3416d3fd0224ccae335129da31f6a550030f1104"
      url "https://github.com/gbr-ufs/tubenoisseur/releases/download/#{version}/tubenoisseur_Linux_arm64.tar.gz"
    end
  end

  name "tubenoisseur"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tubenoisseur"
  bash_completion "completions/bash"
  fish_completion "completions/fish"
  zsh_completion "completions/zsh"

  # No zap stanza required

end
